2025-06-22 16:57:48,320 INFO Session started at 2025-06-22 16:57:48.320241
2025-06-22 16:57:48,357 INFO Processing user: 
2025-06-22 16:58:02,305 INFO initial message sent for 
2025-06-22 16:58:17,689 INFO followup message sent for 
2025-06-22 16:58:17,696 INFO Recorded  to database
2025-06-22 16:58:20,397 INFO Skipping already contacted: 
2025-06-22 16:58:21,703 INFO Processing user: Anis BEN YOUSSEF
2025-06-22 16:58:33,510 INFO initial message sent for Anis BEN YOUSSEF
2025-06-22 16:58:44,717 INFO followup message sent for Anis BEN YOUSSEF
2025-06-22 16:58:44,720 INFO Recorded Anis BEN YOUSSEF to database
2025-06-22 16:58:47,801 INFO Processing user: Romain BEZOLLES
2025-06-22 16:59:01,128 INFO initial message sent for Romain BEZOLLES
2025-06-22 16:59:15,515 INFO followup message sent for Romain BEZOLLES
2025-06-22 16:59:15,516 INFO Recorded Romain BEZOLLES to database
2025-06-22 16:59:16,666 INFO Processing user: Joffrey TERRINE
2025-06-22 16:59:31,665 INFO initial message sent for Joffrey TERRINE
2025-06-22 16:59:46,109 INFO followup message sent for Joffrey TERRINE
2025-06-22 16:59:46,111 INFO Recorded Joffrey TERRINE to database
2025-06-22 16:59:52,634 INFO Skipping already contacted: 
2025-06-22 16:59:54,818 INFO Processing user: Joseph MARTINO
2025-06-22 17:00:07,878 INFO initial message sent for Joseph MARTINO
2025-06-22 17:00:21,653 INFO followup message sent for Joseph MARTINO
2025-06-22 17:00:21,654 INFO Recorded Joseph MARTINO to database
2025-06-22 17:00:23,833 INFO Processing user: Mathias PAYET
2025-06-22 17:00:38,768 INFO initial message sent for Mathias PAYET
2025-06-22 17:00:54,490 INFO followup message sent for Mathias PAYET
2025-06-22 17:00:54,491 INFO Recorded Mathias PAYET to database
2025-06-22 17:00:56,490 INFO Processing user: Mickaella SAMBA
2025-06-22 17:01:10,334 INFO initial message sent for Mickaella SAMBA
2025-06-22 17:01:22,104 INFO followup message sent for Mickaella SAMBA
2025-06-22 17:01:22,106 INFO Recorded Mickaella SAMBA to database
2025-06-22 17:01:23,705 INFO Processing user: Julien LISITA
2025-06-22 17:01:36,919 INFO initial message sent for Julien LISITA
2025-06-22 17:01:51,875 INFO followup message sent for Julien LISITA
2025-06-22 17:01:51,876 INFO Recorded Julien LISITA to database
2025-06-22 17:01:58,785 INFO Processing user: Jonathan LACOSTE
2025-06-22 17:02:10,800 INFO initial message sent for Jonathan LACOSTE
2025-06-22 17:02:26,918 INFO followup message sent for Jonathan LACOSTE
2025-06-22 17:02:26,919 INFO Recorded Jonathan LACOSTE to database
2025-06-22 17:02:28,753 INFO Skipping already contacted: 
2025-06-22 17:02:30,703 INFO Processing user: Maryse ALVAREZ
2025-06-22 17:02:45,369 INFO initial message sent for Maryse ALVAREZ
2025-06-22 17:02:59,515 INFO followup message sent for Maryse ALVAREZ
2025-06-22 17:02:59,516 INFO Recorded Maryse ALVAREZ to database
2025-06-22 17:03:00,842 INFO Processing user: Assel SULTANGAZIEVA
2025-06-22 17:03:14,061 INFO initial message sent for Assel SULTANGAZIEVA
2025-06-22 17:03:28,190 INFO followup message sent for Assel SULTANGAZIEVA
2025-06-22 17:03:28,190 INFO Recorded Assel SULTANGAZIEVA to database
2025-06-22 17:03:30,644 INFO Processing user: Vincent HAVET
2025-06-22 17:03:41,366 INFO initial message sent for Vincent HAVET
2025-06-22 17:03:53,243 INFO followup message sent for Vincent HAVET
2025-06-22 17:03:53,244 INFO Recorded Vincent HAVET to database
2025-06-22 17:03:59,703 INFO Processing user: Nathalie AMICHOT
2025-06-22 17:04:11,915 ERROR Error sending initial message for Nathalie AMICHOT
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 96, in send_message
    subject_input = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.ID, "contact-objet"))
    )
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/support/wait.py", line 138, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564235c3545a <unknown>
#1 0x5642356da760 <unknown>
#2 0x56423572c127 <unknown>
#3 0x56423572c321 <unknown>
#4 0x56423577ae94 <unknown>
#5 0x564235751e7d <unknown>
#6 0x56423577830b <unknown>
#7 0x564235751c23 <unknown>
#8 0x56423571e4a5 <unknown>
#9 0x56423571f111 <unknown>
#10 0x564235bf9f1b <unknown>
#11 0x564235bfde19 <unknown>
#12 0x564235be0ac9 <unknown>
#13 0x564235bfe9c8 <unknown>
#14 0x564235bc534f <unknown>
#15 0x564235c22a28 <unknown>
#16 0x564235c22c06 <unknown>
#17 0x564235c34336 <unknown>
#18 0x7f4eb826efa8 start_thread
#19 0x7f4eb82f2fcc __clone3

2025-06-22 17:04:12,043 INFO Saved error snapshot for Nathalie AMICHOT at errors/Nathalie AMICHOT_initial_20250622_170411
2025-06-22 17:04:13,108 ERROR Error sending followup message for Nathalie AMICHOT
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 94, in send_message
    contact_button.click(); random_delay()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 121, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 574, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button onclick="actionBoutonMiseEnContact();xiti_page_contacterCourriel(16)" id="boutonMiseEnContact" class="btn btn-primary" type="button">...</button> is not clickable at point (118, 101). Other element would receive the click: <div aria-labelledby="lienAriaPopinMiseEnContact" role="dialog" tabindex="-1" id="PopinMiseEnContact" class="modal fade in" style="display: block;">...</div>
  (Session info: chrome=137.0.7151.103)
Stacktrace:
#0 0x564235c3545a <unknown>
#1 0x5642356da760 <unknown>
#2 0x564235732f9c <unknown>
#3 0x564235730e4a <unknown>
#4 0x56423572e4a2 <unknown>
#5 0x56423572dbc0 <unknown>
#6 0x56423572032d <unknown>
#7 0x564235751e52 <unknown>
#8 0x56423571fcaa <unknown>
#9 0x56423575201e <unknown>
#10 0x56423577830b <unknown>
#11 0x564235751c23 <unknown>
#12 0x56423571e4a5 <unknown>
#13 0x56423571f111 <unknown>
#14 0x564235bf9f1b <unknown>
#15 0x564235bfde19 <unknown>
#16 0x564235be0ac9 <unknown>
#17 0x564235bfe9c8 <unknown>
#18 0x564235bc534f <unknown>
#19 0x564235c22a28 <unknown>
#20 0x564235c22c06 <unknown>
#21 0x564235c34336 <unknown>
#22 0x7f4eb826efa8 start_thread
#23 0x7f4eb82f2fcc __clone3

2025-06-22 17:04:13,237 INFO Saved error snapshot for Nathalie AMICHOT at errors/Nathalie AMICHOT_followup_20250622_170413
2025-06-22 17:04:13,237 INFO Recorded Nathalie AMICHOT to database
2025-06-22 17:04:14,357 ERROR Unexpected error at index 16
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 178, in navigate_profiles
    next_btn.click(); random_delay()
    ~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 121, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 574, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button onclick="xiti_navigation_suivant(16);" title="Suivant" aria-label="Suivant" class="btn btn-default btn-nav next inputDisabled " data-num-profil="1049928569" type="button">...</button> is not clickable at point (161, 35). Other element would receive the click: <div aria-labelledby="lienAriaPopinMiseEnContact" role="dialog" tabindex="-1" id="PopinMiseEnContact" class="modal fade in" style="display: block;">...</div>
  (Session info: chrome=137.0.7151.103)
Stacktrace:
#0 0x564235c3545a <unknown>
#1 0x5642356da760 <unknown>
#2 0x564235732f9c <unknown>
#3 0x564235730e4a <unknown>
#4 0x56423572e4a2 <unknown>
#5 0x56423572dbc0 <unknown>
#6 0x56423572032d <unknown>
#7 0x564235751e52 <unknown>
#8 0x56423571fcaa <unknown>
#9 0x56423575201e <unknown>
#10 0x56423577830b <unknown>
#11 0x564235751c23 <unknown>
#12 0x56423571e4a5 <unknown>
#13 0x56423571f111 <unknown>
#14 0x564235bf9f1b <unknown>
#15 0x564235bfde19 <unknown>
#16 0x564235be0ac9 <unknown>
#17 0x564235bfe9c8 <unknown>
#18 0x564235bc534f <unknown>
#19 0x564235c22a28 <unknown>
#20 0x564235c22c06 <unknown>
#21 0x564235c34336 <unknown>
#22 0x7f4eb826efa8 start_thread
#23 0x7f4eb82f2fcc __clone3

2025-06-22 17:04:14,483 INFO Saved error snapshot for loop_16 at errors/loop_16_navigation_20250622_170414
2025-06-22 17:04:14,483 INFO Session ended at 2025-06-22 17:04:14.483395 after 16 profiles, duration 0:06:26.163154
2025-06-22 17:12:58,497 INFO Session started at 2025-06-22 17:12:58.497317
2025-06-22 17:12:58,527 INFO Processing user: 
2025-06-22 17:13:13,823 INFO initial message sent for 
2025-06-22 17:13:29,430 INFO followup message sent for 
2025-06-22 17:13:29,435 INFO Recorded  to database
2025-06-22 17:13:32,237 INFO Skipping already contacted: 
2025-06-22 17:13:33,826 INFO Skipping already contacted: Anis BEN YOUSSEF
2025-06-22 17:13:36,271 INFO Skipping already contacted: Romain BEZOLLES
2025-06-22 17:13:38,503 INFO Skipping already contacted: Joffrey TERRINE
2025-06-22 17:13:44,899 INFO Skipping already contacted: 
2025-06-22 17:13:46,440 INFO Skipping already contacted: Joseph MARTINO
2025-06-22 17:13:47,753 INFO Skipping already contacted: 
2025-06-22 17:13:49,296 INFO Skipping already contacted: Mathias PAYET
2025-06-22 17:13:51,272 INFO Skipping already contacted: Mickaella SAMBA
2025-06-22 17:14:00,605 INFO Skipping already contacted: Julien LISITA
2025-06-22 17:14:02,567 INFO Skipping already contacted: Jonathan LACOSTE
2025-06-22 17:14:04,085 INFO Skipping already contacted: 
2025-06-22 17:14:05,291 INFO Skipping already contacted: Maryse ALVAREZ
2025-06-22 17:14:06,816 INFO Skipping already contacted: Assel SULTANGAZIEVA
2025-06-22 17:14:15,890 INFO Skipping already contacted: Vincent HAVET
2025-06-22 17:14:18,913 INFO Skipping already contacted: Nathalie AMICHOT
2025-06-22 17:14:20,871 INFO Processing user: Gilles PLAZANET
2025-06-22 17:14:33,222 INFO initial message sent for Gilles PLAZANET
2025-06-22 17:14:46,677 INFO followup message sent for Gilles PLAZANET
2025-06-22 17:14:46,679 INFO Recorded Gilles PLAZANET to database
2025-06-22 17:14:49,293 INFO Processing user: Kevin LEVEQUE
2025-06-22 17:15:00,918 INFO initial message sent for Kevin LEVEQUE
2025-06-22 17:15:16,427 INFO followup message sent for Kevin LEVEQUE
2025-06-22 17:15:16,429 INFO Recorded Kevin LEVEQUE to database
2025-06-22 17:15:18,201 INFO Skipping already contacted: 
2025-06-22 17:15:27,407 INFO Skipping already contacted: 
2025-06-22 17:15:30,264 INFO Processing user: Eddy HOARAU
2025-06-22 17:15:41,263 INFO initial message sent for Eddy HOARAU
2025-06-22 17:15:56,353 INFO followup message sent for Eddy HOARAU
2025-06-22 17:15:56,354 INFO Recorded Eddy HOARAU to database
2025-06-22 17:15:57,804 INFO Processing user: Abdelmoumen MEZIANE TOUKOUKI
2025-06-22 17:16:09,890 INFO initial message sent for Abdelmoumen MEZIANE TOUKOUKI
2025-06-22 17:16:24,587 INFO followup message sent for Abdelmoumen MEZIANE TOUKOUKI
2025-06-22 17:16:24,587 INFO Recorded Abdelmoumen MEZIANE TOUKOUKI to database
2025-06-22 17:16:27,473 INFO Processing user: Julien NEDELLEC
2025-06-22 17:16:38,478 INFO initial message sent for Julien NEDELLEC
2025-06-22 17:16:53,155 INFO followup message sent for Julien NEDELLEC
2025-06-22 17:16:53,156 INFO Recorded Julien NEDELLEC to database
2025-06-22 17:16:55,175 INFO Skipping already contacted: 
2025-06-22 17:17:05,872 INFO Skipping already contacted: Anis BEN YOUSSEF
2025-06-22 17:17:07,795 INFO Processing user: Jeremy VAT
2025-06-22 17:17:18,157 INFO initial message sent for Jeremy VAT
2025-06-22 17:17:32,673 INFO followup message sent for Jeremy VAT
2025-06-22 17:17:32,674 INFO Recorded Jeremy VAT to database
2025-06-22 17:17:34,515 INFO Processing user: Ahmet YIGIT
2025-06-22 17:17:46,954 INFO initial message sent for Ahmet YIGIT
2025-06-22 17:18:02,248 INFO followup message sent for Ahmet YIGIT
2025-06-22 17:18:02,249 INFO Recorded Ahmet YIGIT to database
2025-06-22 17:18:03,466 INFO Processing user: Mohamed GAID
2025-06-22 17:18:14,364 INFO initial message sent for Mohamed GAID
2025-06-22 17:18:28,004 INFO followup message sent for Mohamed GAID
2025-06-22 17:18:28,005 INFO Recorded Mohamed GAID to database
2025-06-22 17:18:30,812 INFO Skipping already contacted: Romain BEZOLLES
2025-06-22 17:18:38,594 INFO Processing user: Wassim SLIMANE
2025-06-22 17:18:51,465 INFO initial message sent for Wassim SLIMANE
2025-06-22 17:19:06,769 INFO followup message sent for Wassim SLIMANE
2025-06-22 17:19:06,771 INFO Recorded Wassim SLIMANE to database
2025-06-22 17:19:09,101 INFO Processing user: Youcef SAIDI
2025-06-22 17:19:21,694 INFO initial message sent for Youcef SAIDI
2025-06-22 17:19:36,395 INFO followup message sent for Youcef SAIDI
2025-06-22 17:19:36,397 INFO Recorded Youcef SAIDI to database
2025-06-22 17:19:37,901 INFO Processing user: Joey PAGES
2025-06-22 17:19:54,035 INFO initial message sent for Joey PAGES
2025-06-22 17:20:06,657 INFO followup message sent for Joey PAGES
2025-06-22 17:20:06,658 INFO Recorded Joey PAGES to database
2025-06-22 17:20:08,141 INFO Processing user: Lillian DARMON
2025-06-22 17:20:21,657 INFO initial message sent for Lillian DARMON
2025-06-22 17:20:35,966 INFO followup message sent for Lillian DARMON
2025-06-22 17:20:35,967 INFO Recorded Lillian DARMON to database
2025-06-22 17:20:38,092 INFO Processing user: Sonia CHAVEPEYRE
2025-06-22 17:20:51,873 INFO initial message sent for Sonia CHAVEPEYRE
2025-06-22 17:21:05,411 INFO followup message sent for Sonia CHAVEPEYRE
2025-06-22 17:21:05,411 INFO Recorded Sonia CHAVEPEYRE to database
2025-06-22 17:21:11,758 INFO Processing user: Theo PORTELLI
2025-06-22 17:21:22,757 INFO initial message sent for Theo PORTELLI
2025-06-22 17:21:34,551 INFO followup message sent for Theo PORTELLI
2025-06-22 17:21:34,553 INFO Recorded Theo PORTELLI to database
2025-06-22 17:21:36,836 INFO Processing user: Leo ALLAIX
2025-06-22 17:21:50,521 INFO initial message sent for Leo ALLAIX
2025-06-22 17:22:04,463 INFO followup message sent for Leo ALLAIX
2025-06-22 17:22:04,464 INFO Recorded Leo ALLAIX to database
2025-06-22 17:22:07,303 INFO Processing user: Raymond LOUA
2025-06-22 17:22:22,037 INFO initial message sent for Raymond LOUA
2025-06-22 17:22:35,790 INFO followup message sent for Raymond LOUA
2025-06-22 17:22:35,791 INFO Recorded Raymond LOUA to database
2025-06-22 17:22:37,882 INFO Skipping already contacted: Joffrey TERRINE
2025-06-22 17:22:40,646 INFO Processing user: Alexandre BELLOFATTO
2025-06-22 17:22:54,138 INFO initial message sent for Alexandre BELLOFATTO
2025-06-22 17:23:07,601 INFO followup message sent for Alexandre BELLOFATTO
2025-06-22 17:23:07,602 INFO Recorded Alexandre BELLOFATTO to database
2025-06-22 17:23:18,166 INFO Processing user: Herve AUFFRET
2025-06-22 17:23:32,684 INFO initial message sent for Herve AUFFRET
2025-06-22 17:23:44,344 INFO followup message sent for Herve AUFFRET
2025-06-22 17:23:44,344 INFO Recorded Herve AUFFRET to database
2025-06-22 17:23:47,182 INFO Processing user: Bryan DARDOUR
2025-06-22 17:23:59,684 INFO initial message sent for Bryan DARDOUR
2025-06-22 17:24:10,504 INFO followup message sent for Bryan DARDOUR
2025-06-22 17:24:10,505 INFO Recorded Bryan DARDOUR to database
2025-06-22 17:24:11,769 INFO Processing user: Michael POURPRIX
2025-06-22 17:24:24,465 INFO initial message sent for Michael POURPRIX
2025-06-22 17:24:39,395 INFO followup message sent for Michael POURPRIX
2025-06-22 17:24:39,396 INFO Recorded Michael POURPRIX to database
2025-06-22 17:24:41,576 INFO Processing user: Benjamin CHOLVIN
2025-06-22 17:24:53,662 INFO initial message sent for Benjamin CHOLVIN
2025-06-22 17:25:08,113 INFO followup message sent for Benjamin CHOLVIN
2025-06-22 17:25:08,114 INFO Recorded Benjamin CHOLVIN to database
2025-06-22 17:25:10,513 INFO Processing user: Elie CELKA
2025-06-22 17:25:19,848 INFO initial message sent for Elie CELKA
2025-06-22 17:25:33,200 INFO followup message sent for Elie CELKA
2025-06-22 17:25:33,201 INFO Recorded Elie CELKA to database
2025-06-22 17:25:43,070 INFO Processing user: Corentin BUSI
2025-06-22 17:25:56,945 INFO initial message sent for Corentin BUSI
2025-06-22 17:26:09,866 INFO followup message sent for Corentin BUSI
2025-06-22 17:26:09,868 INFO Recorded Corentin BUSI to database
2025-06-22 17:26:12,364 INFO Processing user: Anthony ROSSIGNOL
2025-06-22 17:26:24,037 INFO initial message sent for Anthony ROSSIGNOL
2025-06-22 17:26:38,518 INFO followup message sent for Anthony ROSSIGNOL
2025-06-22 17:26:38,519 INFO Recorded Anthony ROSSIGNOL to database
2025-06-22 17:26:39,954 INFO Processing user: Leonard MERCELUS
2025-06-22 17:26:52,861 INFO initial message sent for Leonard MERCELUS
2025-06-22 17:27:06,410 INFO followup message sent for Leonard MERCELUS
2025-06-22 17:27:06,411 INFO Recorded Leonard MERCELUS to database
2025-06-22 17:27:08,925 INFO Processing user: Guillaume PIARD
2025-06-22 17:27:22,009 INFO initial message sent for Guillaume PIARD
2025-06-22 17:27:36,104 INFO followup message sent for Guillaume PIARD
2025-06-22 17:27:36,105 INFO Recorded Guillaume PIARD to database
2025-06-22 17:27:37,987 INFO Processing user: Sebastien HIERSO
2025-06-22 17:27:48,946 INFO initial message sent for Sebastien HIERSO
2025-06-22 17:28:00,646 INFO followup message sent for Sebastien HIERSO
2025-06-22 17:28:00,647 INFO Recorded Sebastien HIERSO to database
2025-06-22 17:28:05,685 INFO Processing user: Woodens JEAN
2025-06-22 17:28:19,892 INFO initial message sent for Woodens JEAN
2025-06-22 17:28:31,500 INFO followup message sent for Woodens JEAN
2025-06-22 17:28:31,501 INFO Recorded Woodens JEAN to database
2025-06-22 17:28:33,733 INFO Processing user: Adrien SORIANO
2025-06-22 17:28:45,603 INFO initial message sent for Adrien SORIANO
2025-06-22 17:28:59,490 INFO followup message sent for Adrien SORIANO
2025-06-22 17:28:59,491 INFO Recorded Adrien SORIANO to database
2025-06-22 17:29:01,413 INFO Processing user: Augustin PREDHOMME
2025-06-22 17:29:14,121 INFO initial message sent for Augustin PREDHOMME
2025-06-22 17:29:27,118 INFO followup message sent for Augustin PREDHOMME
2025-06-22 17:29:27,119 INFO Recorded Augustin PREDHOMME to database
2025-06-22 17:29:29,671 INFO Processing user: Abdessamad HANGUIR
2025-06-22 17:29:42,445 INFO initial message sent for Abdessamad HANGUIR
2025-06-22 17:29:57,479 INFO followup message sent for Abdessamad HANGUIR
2025-06-22 17:29:57,479 INFO Recorded Abdessamad HANGUIR to database
2025-06-22 17:29:59,505 INFO Skipping already contacted: 
2025-06-22 17:30:08,794 INFO Skipping already contacted: 
2025-06-22 17:30:10,723 INFO Processing user: Pierre LAFITTE
2025-06-22 17:30:23,802 INFO initial message sent for Pierre LAFITTE
2025-06-22 17:30:37,325 INFO followup message sent for Pierre LAFITTE
2025-06-22 17:30:37,326 INFO Recorded Pierre LAFITTE to database
2025-06-22 17:30:38,799 INFO Skipping already contacted: Mathias PAYET
2025-06-22 17:30:39,896 INFO Skipping already contacted: 
2025-06-22 17:30:41,145 INFO Skipping already contacted: 
2025-06-22 17:30:48,991 INFO Processing user: Hugo DURAND
2025-06-22 17:31:02,679 INFO initial message sent for Hugo DURAND
2025-06-22 17:31:15,410 INFO followup message sent for Hugo DURAND
2025-06-22 17:31:15,411 INFO Recorded Hugo DURAND to database
2025-06-22 17:31:17,836 INFO Processing user: Steeve MELLET
2025-06-22 17:31:30,666 INFO initial message sent for Steeve MELLET
2025-06-22 17:31:43,769 INFO followup message sent for Steeve MELLET
2025-06-22 17:31:43,772 INFO Recorded Steeve MELLET to database
2025-06-22 17:31:46,105 INFO Processing user: Yassin BAKOUH
2025-06-22 17:32:00,025 INFO initial message sent for Yassin BAKOUH
2025-06-22 17:32:12,619 INFO followup message sent for Yassin BAKOUH
2025-06-22 17:32:12,620 INFO Recorded Yassin BAKOUH to database
2025-06-22 17:32:14,046 INFO Processing user: Thomas POMART
2025-06-22 17:32:26,723 INFO initial message sent for Thomas POMART
2025-06-22 17:32:39,763 INFO followup message sent for Thomas POMART
2025-06-22 17:32:39,764 INFO Recorded Thomas POMART to database
2025-06-22 17:32:41,081 INFO Processing user: Jonathan FAVOREL
2025-06-22 17:32:52,346 INFO initial message sent for Jonathan FAVOREL
2025-06-22 17:33:07,250 INFO followup message sent for Jonathan FAVOREL
2025-06-22 17:33:07,250 INFO Recorded Jonathan FAVOREL to database
2025-06-22 17:33:15,776 INFO Processing user: Makrem AMERI
2025-06-22 17:33:31,605 INFO initial message sent for Makrem AMERI
2025-06-22 17:33:46,515 INFO followup message sent for Makrem AMERI
2025-06-22 17:33:46,517 INFO Recorded Makrem AMERI to database
2025-06-22 17:33:49,091 INFO Processing user: Evan BELROSE
2025-06-22 17:34:01,745 INFO initial message sent for Evan BELROSE
2025-06-22 17:34:14,846 INFO followup message sent for Evan BELROSE
2025-06-22 17:34:14,846 INFO Recorded Evan BELROSE to database
2025-06-22 17:34:16,509 INFO Processing user: Thomas FANTOU
2025-06-22 17:34:28,666 INFO initial message sent for Thomas FANTOU
2025-06-22 17:34:41,545 INFO followup message sent for Thomas FANTOU
2025-06-22 17:34:41,545 INFO Recorded Thomas FANTOU to database
2025-06-22 17:34:43,505 INFO Processing user: Habsatou LY
2025-06-22 17:34:54,972 INFO initial message sent for Habsatou LY
2025-06-22 17:35:09,044 INFO followup message sent for Habsatou LY
2025-06-22 17:35:09,046 INFO Recorded Habsatou LY to database
2025-06-22 17:35:12,058 INFO Processing user: Yvon DELACOURT
2025-06-22 17:35:26,237 INFO initial message sent for Yvon DELACOURT
2025-06-22 17:35:38,827 INFO followup message sent for Yvon DELACOURT
2025-06-22 17:35:38,828 INFO Recorded Yvon DELACOURT to database
2025-06-22 17:35:46,402 INFO Processing user: Sebastien MAILLET
2025-06-22 17:35:58,253 INFO initial message sent for Sebastien MAILLET
2025-06-22 17:36:09,840 INFO followup message sent for Sebastien MAILLET
2025-06-22 17:36:09,840 INFO Recorded Sebastien MAILLET to database
2025-06-22 17:36:12,510 INFO Processing user: Floriane ROBIN
2025-06-22 17:36:25,858 INFO initial message sent for Floriane ROBIN
2025-06-22 17:36:39,984 INFO followup message sent for Floriane ROBIN
2025-06-22 17:36:39,985 INFO Recorded Floriane ROBIN to database
2025-06-22 17:36:42,111 INFO Skipping already contacted: Mickaella SAMBA
2025-06-22 17:36:44,006 INFO Skipping already contacted: Julien LISITA
2025-06-22 17:36:46,755 INFO Skipping already contacted: Jonathan LACOSTE
2025-06-22 17:36:52,801 INFO Processing user: Alexandre PORTERON
2025-06-22 17:37:05,484 INFO initial message sent for Alexandre PORTERON
2025-06-22 17:37:18,795 INFO followup message sent for Alexandre PORTERON
2025-06-22 17:37:18,795 INFO Recorded Alexandre PORTERON to database
2025-06-22 17:37:21,019 INFO Processing user: Emmanuelle REY
2025-06-22 17:37:32,435 INFO initial message sent for Emmanuelle REY
2025-06-22 17:37:44,632 INFO followup message sent for Emmanuelle REY
2025-06-22 17:37:44,633 INFO Recorded Emmanuelle REY to database
2025-06-22 17:37:47,343 INFO Processing user: Kobi THAYENDRAN
2025-06-22 17:37:59,283 INFO initial message sent for Kobi THAYENDRAN
2025-06-22 17:38:14,892 INFO followup message sent for Kobi THAYENDRAN
2025-06-22 17:38:14,893 INFO Recorded Kobi THAYENDRAN to database
2025-06-22 17:38:17,331 INFO Processing user: Gabriel GOMEZ
2025-06-22 17:38:28,909 INFO initial message sent for Gabriel GOMEZ
2025-06-22 17:38:44,854 INFO followup message sent for Gabriel GOMEZ
2025-06-22 17:38:44,855 INFO Recorded Gabriel GOMEZ to database
2025-06-22 17:38:46,706 INFO Processing user: Uarda ALMETA
2025-06-22 17:38:57,634 INFO initial message sent for Uarda ALMETA
2025-06-22 17:39:10,813 INFO followup message sent for Uarda ALMETA
2025-06-22 17:39:10,814 INFO Recorded Uarda ALMETA to database
2025-06-22 17:39:18,429 INFO Processing user: Cyrille MOREL
2025-06-22 17:39:32,074 INFO initial message sent for Cyrille MOREL
2025-06-22 17:39:44,653 INFO followup message sent for Cyrille MOREL
2025-06-22 17:39:44,654 INFO Recorded Cyrille MOREL to database
2025-06-22 17:39:47,293 INFO Processing user: Vincent LANFRANCHI
2025-06-22 17:40:01,065 INFO initial message sent for Vincent LANFRANCHI
2025-06-22 17:40:14,173 INFO followup message sent for Vincent LANFRANCHI
2025-06-22 17:40:14,174 INFO Recorded Vincent LANFRANCHI to database
2025-06-22 17:40:15,328 INFO Processing user: Matthis POIREAU--DERRE
2025-06-22 17:40:25,710 INFO initial message sent for Matthis POIREAU--DERRE
2025-06-22 17:40:42,891 INFO followup message sent for Matthis POIREAU--DERRE
2025-06-22 17:40:42,892 INFO Recorded Matthis POIREAU--DERRE to database
2025-06-22 17:40:45,078 INFO Processing user: Christian SHUNGU KATEHE
2025-06-22 17:40:56,678 INFO initial message sent for Christian SHUNGU KATEHE
2025-06-22 17:41:07,116 INFO followup message sent for Christian SHUNGU KATEHE
2025-06-22 17:41:07,117 INFO Recorded Christian SHUNGU KATEHE to database
2025-06-22 17:41:09,522 INFO Skipping already contacted: Sebastien MAILLET
2025-06-22 17:41:18,255 INFO Processing user: Franck D'ANNIBALE
2025-06-22 17:41:30,406 INFO initial message sent for Franck D'ANNIBALE
2025-06-22 17:41:44,260 INFO followup message sent for Franck D'ANNIBALE
2025-06-22 17:41:44,261 INFO Recorded Franck D'ANNIBALE to database
2025-06-22 17:41:45,605 INFO Processing user: Emilie AZAM
2025-06-22 17:41:57,064 INFO initial message sent for Emilie AZAM
2025-06-22 17:42:11,846 INFO followup message sent for Emilie AZAM
2025-06-22 17:42:11,847 INFO Recorded Emilie AZAM to database
2025-06-22 17:42:14,366 INFO Processing user: Loic POLLATZ
2025-06-22 17:42:27,463 INFO initial message sent for Loic POLLATZ
2025-06-22 17:42:39,629 INFO followup message sent for Loic POLLATZ
2025-06-22 17:42:39,630 INFO Recorded Loic POLLATZ to database
2025-06-22 17:42:41,400 INFO Processing user: Albert LANNE
2025-06-22 17:42:53,717 INFO initial message sent for Albert LANNE
2025-06-22 17:43:08,739 INFO followup message sent for Albert LANNE
2025-06-22 17:43:08,740 INFO Recorded Albert LANNE to database
2025-06-22 17:43:10,618 INFO Skipping already contacted: 
2025-06-22 17:43:20,309 INFO Skipping already contacted: 
2025-06-22 17:43:21,561 INFO Processing user: Tony DUONG
2025-06-22 17:43:34,423 INFO initial message sent for Tony DUONG
2025-06-22 17:43:46,425 INFO followup message sent for Tony DUONG
2025-06-22 17:43:46,425 INFO Recorded Tony DUONG to database
2025-06-22 17:43:47,997 INFO Skipping already contacted: 
2025-06-22 17:43:50,338 INFO Processing user: Benjamin LOUIS
2025-06-22 17:44:03,002 INFO initial message sent for Benjamin LOUIS
2025-06-22 17:44:18,109 INFO followup message sent for Benjamin LOUIS
2025-06-22 17:44:18,110 INFO Recorded Benjamin LOUIS to database
2025-06-22 17:44:19,747 INFO Processing user: Davud ARDIC
2025-06-22 17:44:34,849 INFO initial message sent for Davud ARDIC
2025-06-22 17:44:47,413 INFO followup message sent for Davud ARDIC
2025-06-22 17:44:47,414 INFO Recorded Davud ARDIC to database
2025-06-22 17:44:56,764 INFO Skipping already contacted: 
2025-06-22 17:44:58,122 INFO Processing user: Sebastien DELOR
2025-06-22 17:45:09,946 INFO initial message sent for Sebastien DELOR
2025-06-22 17:45:21,304 INFO followup message sent for Sebastien DELOR
2025-06-22 17:45:21,305 INFO Recorded Sebastien DELOR to database
2025-06-22 17:45:22,923 INFO Processing user: Benoit MAINGON
2025-06-22 17:45:36,545 INFO initial message sent for Benoit MAINGON
2025-06-22 17:45:50,375 INFO followup message sent for Benoit MAINGON
2025-06-22 17:45:50,375 INFO Recorded Benoit MAINGON to database
2025-06-22 17:45:52,544 INFO Processing user: Sujan MANANDHAR
2025-06-22 17:46:07,565 INFO initial message sent for Sujan MANANDHAR
2025-06-22 17:46:22,019 INFO followup message sent for Sujan MANANDHAR
2025-06-22 17:46:22,020 INFO Recorded Sujan MANANDHAR to database
2025-06-22 17:46:25,026 INFO Skipping already contacted: Benjamin CHOLVIN
2025-06-22 17:46:31,329 INFO Skipping already contacted: Anthony ROSSIGNOL
2025-06-22 17:46:32,900 INFO Skipping already contacted: Assel SULTANGAZIEVA
2025-06-22 17:46:34,828 INFO Skipping already contacted: Loic POLLATZ
2025-06-22 17:46:37,348 INFO Processing user: Yahya AARJI
2025-06-22 17:46:51,357 INFO initial message sent for Yahya AARJI
2025-06-22 17:47:04,484 INFO followup message sent for Yahya AARJI
2025-06-22 17:47:04,485 INFO Recorded Yahya AARJI to database
2025-06-22 17:47:05,725 INFO Processing user: Mathias MOUFFRON
2025-06-22 17:47:19,578 INFO initial message sent for Mathias MOUFFRON
2025-06-22 17:47:33,562 INFO followup message sent for Mathias MOUFFRON
2025-06-22 17:47:33,563 INFO Recorded Mathias MOUFFRON to database
2025-06-22 17:47:40,921 INFO Skipping already contacted: Herve AUFFRET
2025-06-22 17:47:42,105 INFO Skipping already contacted: Vincent HAVET
2025-06-22 17:47:44,023 INFO Skipping already contacted: Nathalie AMICHOT
2025-06-22 17:47:45,778 INFO Processing user: Alessandro ALESSANDRO
2025-06-22 17:47:58,104 INFO initial message sent for Alessandro ALESSANDRO
2025-06-22 17:48:10,822 INFO followup message sent for Alessandro ALESSANDRO
2025-06-22 17:48:10,823 INFO Recorded Alessandro ALESSANDRO to database
2025-06-22 17:48:12,012 INFO Processing user: Lea VIAL
2025-06-22 17:48:25,104 INFO initial message sent for Lea VIAL
2025-06-22 17:48:38,550 INFO followup message sent for Lea VIAL
2025-06-22 17:48:38,551 INFO Recorded Lea VIAL to database
2025-06-22 17:48:47,687 INFO Processing user: Youssef EL ATRACH
2025-06-22 17:49:00,083 INFO initial message sent for Youssef EL ATRACH
2025-06-22 17:49:24,440 INFO followup message sent for Youssef EL ATRACH
2025-06-22 17:49:24,460 INFO Recorded Youssef EL ATRACH to database
2025-06-22 17:49:26,213 INFO Processing user: Cerine TRABELSI
2025-06-22 17:49:38,981 INFO initial message sent for Cerine TRABELSI
2025-07-01 12:21:07,048 INFO Session started at 2025-07-01 12:21:07.048939, starting from profile 126
2025-07-01 12:21:07,068 INFO Skipping already contacted: Guillaume PIARD
2025-07-01 12:21:10,329 INFO Processing user: Alexis PRIVAT DE FORTUNIE (Daily count: 1)
2025-07-01 12:21:21,840 INFO initial message sent for Alexis PRIVAT DE FORTUNIE
2025-07-01 12:21:37,243 INFO followup message sent for Alexis PRIVAT DE FORTUNIE
2025-07-01 12:21:37,248 INFO Recorded Alexis PRIVAT DE FORTUNIE to database (Daily total: 1)
2025-07-01 12:21:41,713 INFO Skipping already contacted: Ghassen AMAIMIA
2025-07-01 12:21:46,877 INFO Processing user:  (Daily count: 2)
2025-07-01 12:22:00,302 INFO initial message sent for 
2025-07-01 12:22:13,968 INFO followup message sent for 
2025-07-01 12:22:13,974 INFO Recorded  to database (Daily total: 2)
2025-07-01 12:22:18,109 INFO Processing user: Tina SEMASHKO (Daily count: 3)
2025-07-01 12:22:29,925 INFO initial message sent for Tina SEMASHKO
2025-07-01 12:22:45,130 INFO followup message sent for Tina SEMASHKO
2025-07-01 12:22:45,131 INFO Recorded Tina SEMASHKO to database (Daily total: 3)
2025-07-01 12:23:06,786 INFO Processing user: Virginie LEBRAULT-MOREAU-DELAVAULT (Daily count: 4)
2025-07-01 12:23:17,248 INFO initial message sent for Virginie LEBRAULT-MOREAU-DELAVAULT
2025-07-01 12:23:31,334 INFO followup message sent for Virginie LEBRAULT-MOREAU-DELAVAULT
2025-07-01 12:23:31,337 INFO Recorded Virginie LEBRAULT-MOREAU-DELAVAULT to database (Daily total: 4)
2025-07-01 12:23:36,049 INFO Skipping already contacted: Leo ALLAIX
2025-07-01 12:23:40,720 INFO Processing user: Amandine EBNER (Daily count: 5)
2025-07-01 12:23:53,085 INFO initial message sent for Amandine EBNER
2025-07-01 12:24:06,118 INFO followup message sent for Amandine EBNER
2025-07-01 12:24:06,120 INFO Recorded Amandine EBNER to database (Daily total: 5)
2025-07-01 12:24:09,727 INFO Processing user: Nejib ZARAI (Daily count: 6)
2025-07-01 12:24:19,715 INFO initial message sent for Nejib ZARAI
2025-07-01 12:24:31,317 INFO followup message sent for Nejib ZARAI
2025-07-01 12:24:31,318 INFO Recorded Nejib ZARAI to database (Daily total: 6)
2025-07-01 12:24:36,219 INFO Processing user: Cedric MAUGIRON (Daily count: 7)
2025-07-01 12:24:49,032 INFO initial message sent for Cedric MAUGIRON
2025-07-01 12:25:01,838 INFO followup message sent for Cedric MAUGIRON
2025-07-01 12:25:01,839 INFO Recorded Cedric MAUGIRON to database (Daily total: 7)
2025-07-01 12:25:15,695 INFO Skipping already contacted: 
2025-07-01 12:25:19,194 INFO Processing user: Hamza ABASSI (Daily count: 8)
2025-07-01 12:25:31,159 INFO initial message sent for Hamza ABASSI
2025-07-01 12:25:43,994 INFO followup message sent for Hamza ABASSI
2025-07-01 12:25:43,997 INFO Recorded Hamza ABASSI to database (Daily total: 8)
2025-07-01 12:25:48,949 INFO Processing user: Bryan FOUASSIER (Daily count: 9)
2025-07-01 12:25:49,431 INFO Script interrupted by user
2025-07-01 12:25:49,432 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /session/78baac7676a39b7ef794145037b75862
2025-07-01 12:25:49,433 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb652665450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/78baac7676a39b7ef794145037b75862
2025-07-01 12:25:49,433 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb6526656d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/78baac7676a39b7ef794145037b75862
2025-07-01 12:40:07,979 INFO Session started at 2025-07-01 12:40:07.979426, starting from profile 137
2025-07-01 12:40:08,005 INFO Skipping already contacted: Guillaume PIARD
2025-07-01 12:40:12,449 INFO Processing user: Alban PIRRAUD (Daily count: 9)
2025-07-01 12:40:24,931 ERROR Error sending initial message for Alban PIRRAUD
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 211, in send_message
    subject_input = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.ID, "contact-objet"))
    )
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/support/wait.py", line 138, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560cbb17d45a <unknown>
#1 0x560cbac22760 <unknown>
#2 0x560cbac74127 <unknown>
#3 0x560cbac74321 <unknown>
#4 0x560cbacc2e94 <unknown>
#5 0x560cbac99e7d <unknown>
#6 0x560cbacc030b <unknown>
#7 0x560cbac99c23 <unknown>
#8 0x560cbac664a5 <unknown>
#9 0x560cbac67111 <unknown>
#10 0x560cbb141f1b <unknown>
#11 0x560cbb145e19 <unknown>
#12 0x560cbb128ac9 <unknown>
#13 0x560cbb1469c8 <unknown>
#14 0x560cbb10d34f <unknown>
#15 0x560cbb16aa28 <unknown>
#16 0x560cbb16ac06 <unknown>
#17 0x560cbb17c336 <unknown>
#18 0x7fd5e8deefa8 start_thread
#19 0x7fd5e8e72fcc __clone3

2025-07-01 12:40:25,028 INFO Saved error snapshot for Alban PIRRAUD at errors/Alban PIRRAUD_initial_20250701_124024
2025-07-01 12:40:49,757 ERROR Error sending followup message for Alban PIRRAUD
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 209, in send_message
    contact_button.click(); random_delay()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 121, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 574, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button onclick="actionBoutonMiseEnContact();xiti_page_contacterCourriel(2)" id="boutonMiseEnContact" class="btn btn-primary" type="button">...</button> is not clickable at point (118, 86). Other element would receive the click: <div aria-labelledby="lienAriaPopinMiseEnContact" role="dialog" tabindex="-1" id="PopinMiseEnContact" class="modal fade in" style="display: block;">...</div>
  (Session info: chrome=137.0.7151.103)
Stacktrace:
#0 0x560cbb17d45a <unknown>
#1 0x560cbac22760 <unknown>
#2 0x560cbac7af9c <unknown>
#3 0x560cbac78e4a <unknown>
#4 0x560cbac764a2 <unknown>
#5 0x560cbac75bc0 <unknown>
#6 0x560cbac6832d <unknown>
#7 0x560cbac99e52 <unknown>
#8 0x560cbac67caa <unknown>
#9 0x560cbac9a01e <unknown>
#10 0x560cbacc030b <unknown>
#11 0x560cbac99c23 <unknown>
#12 0x560cbac664a5 <unknown>
#13 0x560cbac67111 <unknown>
#14 0x560cbb141f1b <unknown>
#15 0x560cbb145e19 <unknown>
#16 0x560cbb128ac9 <unknown>
#17 0x560cbb1469c8 <unknown>
#18 0x560cbb10d34f <unknown>
#19 0x560cbb16aa28 <unknown>
#20 0x560cbb16ac06 <unknown>
#21 0x560cbb17c336 <unknown>
#22 0x7fd5e8deefa8 start_thread
#23 0x7fd5e8e72fcc __clone3

2025-07-01 12:40:49,855 INFO Saved error snapshot for Alban PIRRAUD at errors/Alban PIRRAUD_followup_20250701_124049
2025-07-01 12:41:12,340 INFO Recorded Alban PIRRAUD to database (Daily total: 9)
2025-07-01 12:41:12,340 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd737333380>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a03bf103466621df5a5b2112b68af07f/element
2025-07-01 12:41:12,340 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd73734d310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a03bf103466621df5a5b2112b68af07f/element
2025-07-01 12:41:12,341 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd73734ee90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a03bf103466621df5a5b2112b68af07f/element
2025-07-01 12:41:12,341 ERROR Unexpected error at index 138
Traceback (most recent call last):
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
    ~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/http/client.py", line 1333, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1093, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1037, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
                ~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
        self, f"Failed to establish a new connection: {e}"
    ) from e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd737486ea0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 318, in navigate_profiles
    next_btn = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//button[@title='Suivant']"))
    )
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/support/wait.py", line 129, in until
    value = method(self._driver)
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/support/expected_conditions.py", line 622, in _predicate
    target = driver.find_element(*target)  # grab element at locator
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 914, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 445, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ~~~~~~~~~~~~~~~~~~~~~~~~^
        method, url, fields=fields, headers=headers, **urlopen_kw
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50285): Max retries exceeded with url: /session/a03bf103466621df5a5b2112b68af07f/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd737486ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-07-01 12:41:12,348 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7374875c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a03bf103466621df5a5b2112b68af07f/screenshot
2025-07-01 12:41:12,348 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd737369910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a03bf103466621df5a5b2112b68af07f/screenshot
2025-07-01 12:41:12,349 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd737502cf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a03bf103466621df5a5b2112b68af07f/screenshot
2025-07-01 12:41:12,349 ERROR Fatal error in main execution
Traceback (most recent call last):
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
    ~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/http/client.py", line 1333, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1093, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1037, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
                ~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
        self, f"Failed to establish a new connection: {e}"
    ) from e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd737486ea0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 318, in navigate_profiles
    next_btn = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//button[@title='Suivant']"))
    )
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/support/wait.py", line 129, in until
    value = method(self._driver)
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/support/expected_conditions.py", line 622, in _predicate
    target = driver.find_element(*target)  # grab element at locator
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 914, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 445, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ~~~~~~~~~~~~~~~~~~~~~~~~^
        method, url, fields=fields, headers=headers, **urlopen_kw
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50285): Max retries exceeded with url: /session/a03bf103466621df5a5b2112b68af07f/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd737486ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 445, in request
    self.endheaders()
    ~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/http/client.py", line 1333, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1093, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "/usr/lib64/python3.13/http/client.py", line 1037, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 276, in connect
    self.sock = self._new_conn()
                ~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
        self, f"Failed to establish a new connection: {e}"
    ) from e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd737503020>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 426, in main
    navigate_profiles(driver, args.force)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 355, in navigate_profiles
    take_error_snapshot(driver, f"loop_{counter}", "navigation")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 149, in take_error_snapshot
    driver.save_screenshot(f"{base}.png")
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 1010, in save_screenshot
    return self.get_screenshot_as_file(filename)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 985, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 1019, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode("ascii"))
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 1029, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 445, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/_request_methods.py", line 135, in request
    return self.request_encode_url(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<3 lines>...
        **urlopen_kw,
        ^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/_request_methods.py", line 182, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/home/rex/.local/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50285): Max retries exceeded with url: /session/a03bf103466621df5a5b2112b68af07f/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd737503020>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-07-01 12:41:12,352 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd737503570>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a03bf103466621df5a5b2112b68af07f
2025-07-01 12:41:12,353 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd7375038a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a03bf103466621df5a5b2112b68af07f
2025-07-01 12:41:12,353 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd737503ac0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a03bf103466621df5a5b2112b68af07f
2025-07-01 12:42:14,591 INFO Session started at 2025-07-01 12:42:14.591614, starting from profile 138
2025-07-01 12:42:14,609 INFO Skipping already contacted: Guillaume PIARD
2025-07-01 12:42:18,404 INFO Skipping already contacted: Alban PIRRAUD
2025-07-01 12:42:23,859 INFO Processing user: Philippe MATHIEU (Daily count: 10)
2025-07-01 12:42:34,974 INFO initial message sent for Philippe MATHIEU
2025-07-01 12:42:48,655 INFO followup message sent for Philippe MATHIEU
2025-07-01 12:42:48,657 INFO Recorded Philippe MATHIEU to database (Daily total: 10)
2025-07-01 12:43:02,428 INFO Skipping already contacted: Alexis PRIVAT DE FORTUNIE
2025-07-01 12:43:07,278 INFO Skipping already contacted: Ghassen AMAIMIA
2025-07-01 12:43:11,281 INFO Processing user:  (Daily count: 11)
2025-07-01 12:43:25,329 INFO initial message sent for 
2025-07-01 12:43:40,068 INFO followup message sent for 
2025-07-01 12:43:40,069 INFO Recorded  to database (Daily total: 11)
2025-07-01 12:43:44,616 INFO Skipping already contacted: Tina SEMASHKO
2025-07-01 12:43:48,461 INFO Skipping already contacted: Virginie LEBRAULT-MOREAU-DELAVAULT
2025-07-01 12:43:59,560 INFO Skipping already contacted: Leo ALLAIX
2025-07-01 12:44:04,633 INFO Skipping already contacted: Amandine EBNER
2025-07-01 12:44:08,208 INFO Skipping already contacted: Nejib ZARAI
2025-07-01 12:44:12,509 INFO Skipping already contacted: Cedric MAUGIRON
2025-07-01 12:44:16,565 INFO Skipping already contacted: 
2025-07-01 12:44:37,611 INFO Skipping already contacted: Hamza ABASSI
2025-07-01 12:44:41,600 INFO Processing user: Bryan FOUASSIER (Daily count: 12)
2025-07-01 12:44:54,067 INFO initial message sent for Bryan FOUASSIER
2025-07-01 12:45:09,544 INFO followup message sent for Bryan FOUASSIER
2025-07-01 12:45:09,545 INFO Recorded Bryan FOUASSIER to database (Daily total: 12)
2025-07-01 12:45:13,668 INFO Processing user: Ody BIEN-EUGENE (Daily count: 13)
2025-07-01 12:45:25,026 INFO initial message sent for Ody BIEN-EUGENE
2025-07-01 12:45:38,790 INFO followup message sent for Ody BIEN-EUGENE
2025-07-01 12:45:38,791 INFO Recorded Ody BIEN-EUGENE to database (Daily total: 13)
2025-07-01 12:45:42,380 INFO Processing user: Mathieu DELEPINE (Daily count: 14)
2025-07-01 12:45:56,700 INFO initial message sent for Mathieu DELEPINE
2025-07-01 12:46:11,538 INFO followup message sent for Mathieu DELEPINE
2025-07-01 12:46:11,539 INFO Recorded Mathieu DELEPINE to database (Daily total: 14)
2025-07-01 12:46:15,842 INFO Processing user: Thomas NACHAR (Daily count: 15)
2025-07-01 12:46:30,136 INFO initial message sent for Thomas NACHAR
2025-07-01 12:46:43,270 INFO followup message sent for Thomas NACHAR
2025-07-01 12:46:43,271 INFO Recorded Thomas NACHAR to database (Daily total: 15)
2025-07-01 12:46:52,292 INFO Processing user: Fatoumata BAH (Daily count: 16)
2025-07-01 12:47:03,651 INFO initial message sent for Fatoumata BAH
2025-07-01 12:47:17,748 INFO followup message sent for Fatoumata BAH
2025-07-01 12:47:17,749 INFO Recorded Fatoumata BAH to database (Daily total: 16)
2025-07-01 12:47:23,103 INFO Processing user: Lydia HADJ MOHAND (Daily count: 17)
2025-07-01 12:47:34,210 INFO initial message sent for Lydia HADJ MOHAND
2025-07-01 12:47:48,025 INFO followup message sent for Lydia HADJ MOHAND
2025-07-01 12:47:48,026 INFO Recorded Lydia HADJ MOHAND to database (Daily total: 17)
2025-07-01 12:47:52,396 INFO Skipping already contacted: 
2025-07-01 12:47:55,977 INFO Processing user: Georges DIETRICH (Daily count: 18)
2025-07-01 12:48:07,820 INFO initial message sent for Georges DIETRICH
2025-07-01 12:48:20,671 INFO followup message sent for Georges DIETRICH
2025-07-01 12:48:20,673 INFO Recorded Georges DIETRICH to database (Daily total: 18)
2025-07-01 12:48:25,411 INFO Processing user: Adil BELACHEHEB (Daily count: 19)
2025-07-01 12:48:37,428 INFO initial message sent for Adil BELACHEHEB
2025-07-01 12:48:52,203 INFO followup message sent for Adil BELACHEHEB
2025-07-01 12:48:52,204 INFO Recorded Adil BELACHEHEB to database (Daily total: 19)
2025-07-01 12:49:09,263 INFO Skipping already contacted: Adil BELACHEHEB
2025-07-01 12:49:13,674 INFO Processing user: Jeremia LATEVE (Daily count: 20)
2025-07-01 12:49:25,568 INFO initial message sent for Jeremia LATEVE
2025-07-01 12:49:39,981 INFO followup message sent for Jeremia LATEVE
2025-07-01 12:49:39,982 INFO Recorded Jeremia LATEVE to database (Daily total: 20)
2025-07-01 12:49:43,213 INFO Processing user: Yann LE COZ (Daily count: 21)
2025-07-01 12:49:55,936 INFO initial message sent for Yann LE COZ
2025-07-01 12:50:12,033 INFO followup message sent for Yann LE COZ
2025-07-01 12:50:12,034 INFO Recorded Yann LE COZ to database (Daily total: 21)
2025-07-01 12:50:16,006 INFO Skipping already contacted: Yann LE COZ
2025-07-01 12:50:20,466 INFO Processing user: Amina GHARIANI (Daily count: 22)
2025-07-01 12:50:34,312 INFO initial message sent for Amina GHARIANI
2025-07-01 12:50:48,827 INFO followup message sent for Amina GHARIANI
2025-07-01 12:50:48,828 INFO Recorded Amina GHARIANI to database (Daily total: 22)
2025-07-01 12:51:00,237 INFO Processing user: Khadimou DIOP (Daily count: 23)
2025-07-01 12:51:13,281 ERROR Error sending initial message for Khadimou DIOP
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 211, in send_message
    subject_input = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.ID, "contact-objet"))
    )
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/support/wait.py", line 138, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55fc009a045a <unknown>
#1 0x55fc00445760 <unknown>
#2 0x55fc00497127 <unknown>
#3 0x55fc00497321 <unknown>
#4 0x55fc004e5e94 <unknown>
#5 0x55fc004bce7d <unknown>
#6 0x55fc004e330b <unknown>
#7 0x55fc004bcc23 <unknown>
#8 0x55fc004894a5 <unknown>
#9 0x55fc0048a111 <unknown>
#10 0x55fc00964f1b <unknown>
#11 0x55fc00968e19 <unknown>
#12 0x55fc0094bac9 <unknown>
#13 0x55fc009699c8 <unknown>
#14 0x55fc0093034f <unknown>
#15 0x55fc0098da28 <unknown>
#16 0x55fc0098dc06 <unknown>
#17 0x55fc0099f336 <unknown>
#18 0x7f01c08c7fa8 start_thread
#19 0x7f01c094bfcc __clone3

2025-07-01 12:51:13,383 INFO Saved error snapshot for Khadimou DIOP at errors/Khadimou DIOP_initial_20250701_125113
2025-07-01 12:51:38,145 ERROR Error sending followup message for Khadimou DIOP
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 209, in send_message
    contact_button.click(); random_delay()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 121, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 574, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button onclick="actionBoutonMiseEnContact();xiti_page_contacterCourriel(28)" id="boutonMiseEnContact" class="btn btn-primary" type="button">...</button> is not clickable at point (118, 86). Other element would receive the click: <div aria-labelledby="lienAriaPopinMiseEnContact" role="dialog" tabindex="-1" id="PopinMiseEnContact" class="modal fade in" style="display: block;">...</div>
  (Session info: chrome=137.0.7151.103)
Stacktrace:
#0 0x55fc009a045a <unknown>
#1 0x55fc00445760 <unknown>
#2 0x55fc0049df9c <unknown>
#3 0x55fc0049be4a <unknown>
#4 0x55fc004994a2 <unknown>
#5 0x55fc00498bc0 <unknown>
#6 0x55fc0048b32d <unknown>
#7 0x55fc004bce52 <unknown>
#8 0x55fc0048acaa <unknown>
#9 0x55fc004bd01e <unknown>
#10 0x55fc004e330b <unknown>
#11 0x55fc004bcc23 <unknown>
#12 0x55fc004894a5 <unknown>
#13 0x55fc0048a111 <unknown>
#14 0x55fc00964f1b <unknown>
#15 0x55fc00968e19 <unknown>
#16 0x55fc0094bac9 <unknown>
#17 0x55fc009699c8 <unknown>
#18 0x55fc0093034f <unknown>
#19 0x55fc0098da28 <unknown>
#20 0x55fc0098dc06 <unknown>
#21 0x55fc0099f336 <unknown>
#22 0x7f01c08c7fa8 start_thread
#23 0x7f01c094bfcc __clone3

2025-07-01 12:51:38,216 INFO Saved error snapshot for Khadimou DIOP at errors/Khadimou DIOP_followup_20250701_125138
2025-07-01 12:52:01,901 INFO Recorded Khadimou DIOP to database (Daily total: 23)
2025-07-01 12:52:03,992 WARNING Click intercepted at profile 166, attempting recovery
2025-07-01 12:52:04,095 INFO Saved error snapshot for intercept_166 at errors/intercept_166_navigation_20250701_125203
2025-07-01 12:52:30,007 INFO Processing user: Leo GONZALEZ (Daily count: 24)
2025-07-01 12:52:31,063 ERROR Error sending initial message for Leo GONZALEZ
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 209, in send_message
    contact_button.click(); random_delay()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 121, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 574, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button onclick="actionBoutonMiseEnContact();xiti_page_contacterCourriel(29)" id="boutonMiseEnContact" class="btn btn-primary" type="button">...</button> is not clickable at point (118, 86). Other element would receive the click: <div aria-labelledby="lienAriaPopinMiseEnContact" role="dialog" tabindex="-1" id="PopinMiseEnContact" class="modal fade in" style="display: block;">...</div>
  (Session info: chrome=137.0.7151.103)
Stacktrace:
#0 0x55fc009a045a <unknown>
#1 0x55fc00445760 <unknown>
#2 0x55fc0049df9c <unknown>
#3 0x55fc0049be4a <unknown>
#4 0x55fc004994a2 <unknown>
#5 0x55fc00498bc0 <unknown>
#6 0x55fc0048b32d <unknown>
#7 0x55fc004bce52 <unknown>
#8 0x55fc0048acaa <unknown>
#9 0x55fc004bd01e <unknown>
#10 0x55fc004e330b <unknown>
#11 0x55fc004bcc23 <unknown>
#12 0x55fc004894a5 <unknown>
#13 0x55fc0048a111 <unknown>
#14 0x55fc00964f1b <unknown>
#15 0x55fc00968e19 <unknown>
#16 0x55fc0094bac9 <unknown>
#17 0x55fc009699c8 <unknown>
#18 0x55fc0093034f <unknown>
#19 0x55fc0098da28 <unknown>
#20 0x55fc0098dc06 <unknown>
#21 0x55fc0099f336 <unknown>
#22 0x7f01c08c7fa8 start_thread
#23 0x7f01c094bfcc __clone3

2025-07-01 12:52:31,168 INFO Saved error snapshot for Leo GONZALEZ at errors/Leo GONZALEZ_initial_20250701_125231
2025-07-01 12:52:55,833 ERROR Error sending followup message for Leo GONZALEZ
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 209, in send_message
    contact_button.click(); random_delay()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 121, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 574, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button onclick="actionBoutonMiseEnContact();xiti_page_contacterCourriel(29)" id="boutonMiseEnContact" class="btn btn-primary" type="button">...</button> is not clickable at point (118, 86). Other element would receive the click: <div aria-labelledby="lienAriaPopinMiseEnContact" role="dialog" tabindex="-1" id="PopinMiseEnContact" class="modal fade in" style="display: block;">...</div>
  (Session info: chrome=137.0.7151.103)
Stacktrace:
#0 0x55fc009a045a <unknown>
#1 0x55fc00445760 <unknown>
#2 0x55fc0049df9c <unknown>
#3 0x55fc0049be4a <unknown>
#4 0x55fc004994a2 <unknown>
#5 0x55fc00498bc0 <unknown>
#6 0x55fc0048b32d <unknown>
#7 0x55fc004bce52 <unknown>
#8 0x55fc0048acaa <unknown>
#9 0x55fc004bd01e <unknown>
#10 0x55fc004e330b <unknown>
#11 0x55fc004bcc23 <unknown>
#12 0x55fc004894a5 <unknown>
#13 0x55fc0048a111 <unknown>
#14 0x55fc00964f1b <unknown>
#15 0x55fc00968e19 <unknown>
#16 0x55fc0094bac9 <unknown>
#17 0x55fc009699c8 <unknown>
#18 0x55fc0093034f <unknown>
#19 0x55fc0098da28 <unknown>
#20 0x55fc0098dc06 <unknown>
#21 0x55fc0099f336 <unknown>
#22 0x7f01c08c7fa8 start_thread
#23 0x7f01c094bfcc __clone3

2025-07-01 12:52:55,938 INFO Saved error snapshot for Leo GONZALEZ at errors/Leo GONZALEZ_followup_20250701_125255
2025-07-01 12:53:19,527 INFO Recorded Leo GONZALEZ to database (Daily total: 24)
2025-07-01 12:53:21,576 WARNING Click intercepted at profile 167, attempting recovery
2025-07-01 12:53:21,662 INFO Saved error snapshot for intercept_167 at errors/intercept_167_navigation_20250701_125321
2025-07-01 12:53:46,574 INFO Processing user: Paul LE COZ (Daily count: 25)
2025-07-01 12:53:47,627 ERROR Error sending initial message for Paul LE COZ
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 209, in send_message
    contact_button.click(); random_delay()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 121, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 574, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button onclick="actionBoutonMiseEnContact();xiti_page_contacterCourriel(30)" id="boutonMiseEnContact" class="btn btn-primary" type="button">...</button> is not clickable at point (118, 86). Other element would receive the click: <div aria-labelledby="lienAriaPopinMiseEnContact" role="dialog" tabindex="-1" id="PopinMiseEnContact" class="modal fade in" style="display: block;">...</div>
  (Session info: chrome=137.0.7151.103)
Stacktrace:
#0 0x55fc009a045a <unknown>
#1 0x55fc00445760 <unknown>
#2 0x55fc0049df9c <unknown>
#3 0x55fc0049be4a <unknown>
#4 0x55fc004994a2 <unknown>
#5 0x55fc00498bc0 <unknown>
#6 0x55fc0048b32d <unknown>
#7 0x55fc004bce52 <unknown>
#8 0x55fc0048acaa <unknown>
#9 0x55fc004bd01e <unknown>
#10 0x55fc004e330b <unknown>
#11 0x55fc004bcc23 <unknown>
#12 0x55fc004894a5 <unknown>
#13 0x55fc0048a111 <unknown>
#14 0x55fc00964f1b <unknown>
#15 0x55fc00968e19 <unknown>
#16 0x55fc0094bac9 <unknown>
#17 0x55fc009699c8 <unknown>
#18 0x55fc0093034f <unknown>
#19 0x55fc0098da28 <unknown>
#20 0x55fc0098dc06 <unknown>
#21 0x55fc0099f336 <unknown>
#22 0x7f01c08c7fa8 start_thread
#23 0x7f01c094bfcc __clone3

2025-07-01 12:53:47,746 INFO Saved error snapshot for Paul LE COZ at errors/Paul LE COZ_initial_20250701_125347
2025-07-01 12:54:12,448 ERROR Error sending followup message for Paul LE COZ
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 209, in send_message
    updated = pd.concat([contacted_df, new], ignore_index=True)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 121, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 574, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button onclick="actionBoutonMiseEnContact();xiti_page_contacterCourriel(30)" id="boutonMiseEnContact" class="btn btn-primary" type="button">...</button> is not clickable at point (118, 86). Other element would receive the click: <div aria-labelledby="lienAriaPopinMiseEnContact" role="dialog" tabindex="-1" id="PopinMiseEnContact" class="modal fade in" style="display: block;">...</div>
  (Session info: chrome=137.0.7151.103)
Stacktrace:
#0 0x55fc009a045a <unknown>
#1 0x55fc00445760 <unknown>
#2 0x55fc0049df9c <unknown>
#3 0x55fc0049be4a <unknown>
#4 0x55fc004994a2 <unknown>
#5 0x55fc00498bc0 <unknown>
#6 0x55fc0048b32d <unknown>
#7 0x55fc004bce52 <unknown>
#8 0x55fc0048acaa <unknown>
#9 0x55fc004bd01e <unknown>
#10 0x55fc004e330b <unknown>
#11 0x55fc004bcc23 <unknown>
#12 0x55fc004894a5 <unknown>
#13 0x55fc0048a111 <unknown>
#14 0x55fc00964f1b <unknown>
#15 0x55fc00968e19 <unknown>
#16 0x55fc0094bac9 <unknown>
#17 0x55fc009699c8 <unknown>
#18 0x55fc0093034f <unknown>
#19 0x55fc0098da28 <unknown>
#20 0x55fc0098dc06 <unknown>
#21 0x55fc0099f336 <unknown>
#22 0x7f01c08c7fa8 start_thread
#23 0x7f01c094bfcc __clone3

2025-07-01 12:54:12,529 INFO Saved error snapshot for Paul LE COZ at errors/Paul LE COZ_followup_20250701_125412
2025-07-01 12:54:36,159 INFO Recorded Paul LE COZ to database (Daily total: 25)
2025-07-01 12:54:38,168 WARNING Click intercepted at profile 168, attempting recovery
2025-07-01 12:54:38,284 INFO Saved error snapshot for intercept_168 at errors/intercept_168_navigation_20250701_125438
2025-07-01 12:55:03,667 INFO Processing user: Laurent THIREAU (Daily count: 26)
2025-07-01 12:55:04,734 ERROR Error sending initial message for Laurent THIREAU
Traceback (most recent call last):
  File "/home/rex/Documents/client_projects/durand_upwork/connect3.py", line 209, in send_message
    updated = pd.concat([contacted_df, new], ignore_index=True)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 121, in click
    self._execute(Command.CLICK_ELEMENT)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webelement.py", line 574, in _execute
    return self._parent.execute(command, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/rex/.local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button onclick="actionBoutonMiseEnContact();xiti_page_contacterCourriel(33)" id="boutonMiseEnContact" class="btn btn-primary" type="button">...</button> is not clickable at point (118, 86). Other element would receive the click: <div aria-labelledby="lienAriaPopinMiseEnContact" role="dialog" tabindex="-1" id="PopinMiseEnContact" class="modal fade in" style="display: block;">...</div>
  (Session info: chrome=137.0.7151.103)
Stacktrace:
#0 0x55fc009a045a <unknown>
#1 0x55fc00445760 <unknown>
#2 0x55fc0049df9c <unknown>
#3 0x55fc0049be4a <unknown>
#4 0x55fc004994a2 <unknown>
#5 0x55fc00498bc0 <unknown>
#6 0x55fc0048b32d <unknown>
#7 0x55fc004bce52 <unknown>
#8 0x55fc0048acaa <unknown>
#9 0x55fc004bd01e <unknown>
#10 0x55fc004e330b <unknown>
#11 0x55fc004bcc23 <unknown>
#12 0x55fc004894a5 <unknown>
#13 0x55fc0048a111 <unknown>
#14 0x55fc00964f1b <unknown>
#15 0x55fc00968e19 <unknown>
#16 0x55fc0094bac9 <unknown>
#17 0x55fc009699c8 <unknown>
#18 0x55fc0093034f <unknown>
#19 0x55fc0098da28 <unknown>
#20 0x55fc0098dc06 <unknown>
#21 0x55fc0099f336 <unknown>
#22 0x7f01c08c7fa8 start_thread
#23 0x7f01c094bfcc __clone3

2025-07-01 12:55:04,847 INFO Saved error snapshot for Laurent THIREAU at errors/Laurent THIREAU_initial_20250701_125504
2025-07-01 12:55:43,489 INFO followup message sent for Laurent THIREAU
2025-07-01 12:55:43,490 INFO Recorded Laurent THIREAU to database (Daily total: 26)
2025-07-01 12:55:48,387 INFO Processing user: Lionel PAOFAI (Daily count: 27)
2025-07-01 12:56:03,029 INFO initial message sent for Lionel PAOFAI
2025-07-01 12:56:15,172 INFO followup message sent for Lionel PAOFAI
2025-07-01 12:56:15,173 INFO Recorded Lionel PAOFAI to database (Daily total: 27)
2025-07-01 12:56:36,333 INFO Processing user: Ad KOUD DE MAURISA (Daily count: 28)
2025-07-01 12:56:49,880 INFO initial message sent for Ad KOUD DE MAURISA
2025-07-01 12:56:56,642 INFO Script interrupted by user
2025-07-01 12:56:56,643 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /session/05334ee10afe6b97617d10786f59f797
2025-07-01 12:56:56,644 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f67720f9310>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/05334ee10afe6b97617d10786f59f797
2025-07-01 12:56:56,644 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f67720fa490>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/05334ee10afe6b97617d10786f59f797
